jobs:
- job: linux

  pool: default

  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 --version
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.10.0
        pip3 install twine
      displayName: Install dependencies
    - bash: |
        sed -i 's/name\=\"triton\"/name="triton-nightly"/g' python/setup.py
        sed -i -r "s/version\=\"(.*)\"/version=\"\1-dev`date '+%Y%m%d'`\"/g" python/setup.py
        echo "" >> python/setup.cfg
        echo "[build_ext]" >> python/setup.cfg
        echo "base-dir=/project" >> python/setup.cfg
      displayName: Patch setup.py
    - bash: |
       export CIBW_BEFORE_BUILD="pip install cmake"
       export CIBW_BUILD="cp36-manylinux_x86_64"
       python3 -m cibuildwheel python --output-dir wheelhouse
     displayName: Build wheels
   - task: PublishBuildArtifacts@1
     inputs: {pathtoPublish: 'wheelhouse'}
    - bash: |
        python3 -m twine upload wheelhouse/* -u $(PYPI_USERNAME) -p $(PYPI_PASSWORD) 
      displayName: Upload wheels to PyPI