jobs:
- job: linux

  pool:
    name: default

  strategy:
    matrix:
      Python36:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.10.0
      displayName: Install dependencies
    - bash: |
        cibuildwheel --output-dir wheelhouse python
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}