name: CI

on:
  pull_request:
    types:
    - '*'
  push:
    branches:
    - master

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/phil0342
            azure-pipeline-name: 'ptillet.triton'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}