name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Triggers the workflow on pull request events Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        name: Call Azure Pipeline
        #runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/phil0342
            azure-pipeline-name: 'ptillet.triton'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}