name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

- name: Azure Pipelines Action
  uses: Azure/pipelines@v1
  with:
    azure-devops-project-url: https://dev.azure.com/phil0342
    azure-pipeline-name: 'ptillet.triton'
    azure-devops-token: ${{secrets.AZURE_DEVOPS_TOKEN}}